name: build-and-test

on:
  pull_request:
    branches: [main]
  release:
    types: [published]
 

jobs:
  build-and-test:

    runs-on: [self-hosted, linux, x64]

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - run: verify_workflows

    - name: Set up node.js (${{ matrix.node-version }})
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up java (jdk-11)
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Log originating commit ID
      run: echo "full_sha1=$(git cat-file -p HEAD | grep parent | tail -1 | cut -d' ' -f2)" >> $GITHUB_ENV 
 
    - name: Tag revision for DEV
      if: github.event_name == 'pull_request'
      run: echo "REVISION=#${{ github.event.number }}.$(git rev-parse --short ${{ env.full_sha1 }})" >> $GITHUB_ENV

    - name: Tag revision for SPRINT
      if: github.event_name == 'release'
      run: echo "REVISION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

    - name: Install client dependencies
      run: cache_dependencies client

    - name: Install server dependencies
      run: cache_dependencies server

    - name: Prepare Codeclimate reporting tools
      env:
        GIT_COMMIT_SHA: ${{ env.full_sha1 }} 
        GIT_BRANCH: ${{ github.head_ref }}
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build

    - name: Run client tests
      run: npm test --prefix client
      
    - name: Bundle client with webpack
      run: npm run prodClient --prefix client
      
    - name: Build & test server with maven
      run: mvn -f server --global-settings server/.m2/settings.xml -Drevision=${{ env.REVISION }} verify

    - name: Postman Tests for DEV
      env:
        REVISION: ${{ env.REVISION }}
      run: postman DEV
      if: github.event_name == 'pull_request'

    - name: Postman Tests for SPRINT
      env:
        REVISION: ${{ env.REVISION }}
      run: postman SPRINT
      if: github.event_name == 'release'
 
    - name: Deploy server for DEV
      env:
        REVISION: ${{ env.REVISION }}
      run: build-test-deploy DEV
      if: github.event_name == 'pull_request'

    - name: Deploy server for SPRINT
      env:
        REVISION: ${{ env.REVISION }}
      run: build-test-deploy SPRINT
      if: github.event_name == 'release'

    - name: Finish and report Codeclimate statistics
      env:
        GIT_COMMIT_SHA: ${{ env.full_sha1 }} 
        GIT_BRANCH: ${{ github.head_ref }}
        JACOCO_SOURCE_PATH: server/src/main/java
      run: |
        ./cc-test-reporter format-coverage -t jacoco target/site/jacoco/jacoco.xml --output "codeclimate.java.json"
        ./cc-test-reporter format-coverage -t clover target/coverage/client/clover.xml --output "codeclimate.js.json"
        ./cc-test-reporter sum-coverage --output "codeclimate.combined.json" codeclimate.*.json
        ./cc-test-reporter upload-coverage --input "codeclimate.combined.json"